### ISSUE TITLE
Clang error: unused variable 't4' in hlsl++_quaternion.h

### ISSUE THREAD

**Issue by egorodet** [redorav/hlslpp#69] opened 2023-04-21 18:53 UTC
I get "unused variable" error in file `hlsl++_quaternion.h` when compiling latest release `3.3` with Clang:

```
../include/hlsl++_quaternion.h:179:8: error: unused variable 't4' [-Werror,-Wunused-variable]
                n128 t4         = _hlslpp_perm_xxxx_ps(t); // Contains t, t, t, t
```

It would be nice to build HLSL++ in CI with maximum warning and error level, i.e. `-Werror` for Clang, `/W4 /WX` for MSVC to prevent such errors in future.

**Comment by redorav** [comment] 2023-04-21 19:00
Yes, I have that pending. The problem is that there are many unused variables that aren't a problem as I only use them to instantiate function and don't use the results. I could create a macro unused_variable or something like that to avoid it. It certainly needs fixing. I'll address it right away

**Comment by redorav** [comment] 2023-04-21 19:01
Fixed via 3305152eda7f70a03e88e5899f399ff188bd1a78

**Closed by redorav** 2023-04-21 19:01 UTC
Labels: bug

**Comment by redorav** [comment] 2023-04-21 19:06
I've made a bug here so you can track it for the future https://github.com/redorav/hlslpp/issues/70#issue-1678969161

**Comment by egorodet** [comment] 2023-04-21 19:18
Thank you! I found this particular error during compilation of my project with HLSL++ 3.3. It was a problem of HLSL++ upgrade to v3.3 because my project is using maximum compilation level. I just want to clarify that I don't really care about unused variables in the unit tests of HLSL++, but it's extremely important to have zero warnings and errors in main headers of the external libraries.

**Comment by redorav** [comment] 2023-04-21 19:20
Yes, I agree. What I mean is that I cannot promote warnings as errors just yet because there are many false positives that come from the unit tests. I have been a bit careless in that regard. I'll see if I can find some time this weekend to do something about it, or incrementally take care of it. Thanks for your continued help. I've created 3.3.1 in case you feel more comfortable upgrading to releases

**Comment by egorodet** [comment] 2023-04-21 19:27
Thanks! It's really more convenient to upgrade to release tag since I use [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake) for external library management, which pulls library sources by version/tag.

Btw, if you're building unit tests with C++17 you may use [[[maybe_unused]]](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused) attribute to ignore those unused variables.
